### ISSUE TITLE
HTML-Editor opens multiple times

### ISSUE THREAD

**Issue by marcelgo** [infopark/scrivito_editors#31]
When using 0.40.0-rc2 and editing a html-attribut with:

```
 = scrivito_tag(:div, widget, :content)
```

I'm not able to insert any content, because the editor just opens again and again.

![input](https://cloud.githubusercontent.com/assets/731013/5896894/8ec62c74-a53d-11e4-89bc-76f24c602d8f.gif)

In the browser console, I get an error:

![console](https://cloud.githubusercontent.com/assets/731013/5896912/ca1c6a86-a53d-11e4-8c6f-77b7eb44807a.jpg)

**Comment by spiderpug** [comment]
The problem here is that the redactor editor 'active' class is different than the code assumes:

`redactor_editor` vs. `redactor-editor`

![screen shot 2015-01-26 at 09 53 29](https://cloud.githubusercontent.com/assets/2295856/5897176/39818b92-a541-11e4-8afe-951c95544de2.png)

https://github.com/infopark/scrivito_editors/blob/develop/app/assets/javascripts/scrivito_editors/html_editor.js.coffee#L103-L105

Using `redactor-editor` works. I must assume there is a better way to determine if the redactor is loaded than checking the css classes , but what do I know.

**Comment by marcelgo** [comment]
We had an copy of the html editor js in our application. This was because of a migration or an earlier issue: "html editor: use patched version that resolves troubles when creating links". After removing the copy of the file, the editor works fine again.

**Comment by dcsaszar** [comment]
OK, I'm going to add a release note
